### ISSUE TITLE
Autogit does not quit/report on error

### ISSUE THREAD

**Issue by haringsrob** [combell/autogit-reference#4]
I am setting up a deployment pipeline using CI and autogit.

However, I notice that even if a command fails (for example composer install) it continues the script.

I believe that instead of continuing it should result in a non 0 exit code so that the pipeline/CLI knows the command failed?

Is there any documentation about this?

**Comment by coudenysj** [comment]
We use the [post-receive git hook](https://git-scm.com/docs/githooks#post-receive) at our end and leverage that to create autogit logic.

> This hook does not affect the outcome of git receive-pack, as it is called after the real work is done.

Because the post-receive hook is done after the real work, git doesn't check its return value, as it cannot affect the outcome of the push anymore. It is just kind enough to pass the output of that script to the client (hence the output you receive when pushing changes to the combell remote).

What you could do, is to catch that output in your pipeline, and do some string processing to determine if a deploy was successfully completed or not.

Autogit does, however, check the outcome of the commands it executes and stops the commands if one fails.

I hope that answers your question, and you'll be able to successfully complete that CI pipeline!

**Comment by haringsrob** [comment]
Hey @coudenysj,

Ok so far so good, I managed to capture the output and fail the pipeline based on that.

What I cannot seem to get to is to make it stop the deployment in case a script fails.


checkout/{branch}/current is a symlink pointing to the latest release. This symlink is updated at the end of a successful deployment. **If the deployment fails in any step the current symlink still points to the old release**.

Example that I use:
```
#!/usr/bin/env bash
set -e
composer install --no-dev --no-interaction || (echo "AUTOGIT FAILED: Composer install" && exit 1)
npm install || (echo "AUTOGIT FAILED: npm install" && exit 1)
npm run prod || (echo "AUTOGIT FAILED: npm build" && exit 1)
exit 1 # Test
```

<img width="677" alt="Screenshot 2022-01-13 at 12 59 30" src="https://user-images.githubusercontent.com/866743/149326636-756e22db-891b-461d-a7e3-987c3513a812.png">

**Comment by haringsrob** [comment]
<img width="677" alt="Screenshot 2022-01-13 at 12 59 30" src="https://user-images.githubusercontent.com/866743/149326449-b5438cb1-216c-43ac-b256-61742a53298b.png">

**Comment by haringsrob** [comment]
Door dus de exit 0 weg te halen werkt het wel.

Ik dacht (omdat deze overal staat) deze nodig was, maar niet dus :).
